### ISSUE TITLE
[2pts] Setup Kanban Board for Recipe App Project (Group Task)

### ISSUE THREAD

**Issue by fezzopro** [fezzopro/recipe_app#1]
## ISSUE DESCRIPTION

The following project concerns a Recipe application that will be developed using the Ruby on Rails framework. The [Recipe App Kanban Board Setup](https://github.com/users/fezzopro/projects/10/views/1?layout=board) can be accessed via this link.

To refresh on the requirements visit [Sneak peek: Recipe app](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/buisness_requirements.md)

## TEAM MEMBERS

1. [Felix KAMANA](https://github.com/fezzopro)
2. [Paul Tesfaye](https://github.com/Paul-tes)

**Comment by Davidosky007** [comment]
Hi @fezzopro @Paul-tes 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has a broken link, kindly provide a link that leads to the Kanban board 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by prolajumokeoni** [comment]
Hi @fezzopro and @Paul-tes 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️  Good setup



## Required Changes ♻️

- [ ] Kindly delete the `no status` column on your board, all cards in `no status` column should should be moved to the `todo` column  you should have only four columns: Todo, In Progress, In Review, Done👍🏿 
![Screenshot_171](https://github.com/fezzopro/recipe_app/assets/69638013/765a3e12-c408-4bf5-b551-706d91b9110c)

- [ ] Kindly add a card to `make sure there are no N+1 queries happening`


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ichala** [comment]
Hi Student  ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
 
![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

# To Highlight 💪🏻

- Changes Implemented ✔️ 


 Good job implementing the requirements  :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Optional Suggestions  :

- N/A


**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
